project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Social Opinions Over Time: Visualizing Public Opinion on Abortion, Affirmative Action, and Capital Punishment from 1972-2022"
  author:
    - Jared Donohue (jjd2203)
    - Morgan Jackson (mcj2158)
    - Kenza Slaoui (ks4300)
  repo-url: https://github.com/jdonohue44/GeneralSocialSurveyVisualizations
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: darkly
    code-fold: true


